version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.141
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
     - nexus-data:/nexus-data