version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.141
    build: './jenkins-withdocker'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  nexus:
    image: sonatype/nexus3:3.13.0
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
  bitbucket:
    image: atlassian/bitbucket-server:5.7.1
    volumes:
      - bitbucket_home:/var/atlassian/application-data/bitbucket
    ports:
      - 7990:7990
      - 7999:7999

volumes:
  jenkins_home:
  nexus-data:
  bitbucket_home: